# .travis.yml
language: node_js

os:
  - linux
  - osx

node_js:
  - "8"

install:
  - cd backend
  - npm install
  - cd ../frontend
  - npm install
  - cd ..

script:
# Check frontend can be run without error
  - cd frontend
  - npm run dev & sleep 10
# Build frontend for production
  - npm run build
# Check backend can be run without error
  - cd ../backend
  - npm start & sleep 5
  - cd ..
