# .travis.yml
language: node_js

node_js:
  - "node"

branches:
  only:
    - master

install:
  - cd backend
  - npm install
  - cd ../frontend
  - npm install

script:
  - npm run build
  - cd ../backend
  - npm start &
