# .travis.yml
language: node_js

node_js:
  - "node"

install:
  - cd backend
  - npm install
  - cd ../frontend
  - npm install
  - cd ..

script:
# Check frontend can be run without error
  - cd frontend
  - DEBUG=backend:*
  - npm run dev & sleep 10
# Build frontend for production
  - npm run build --report
  - cd ../backend
# Check backend can be run without error
  - npm start & sleep 5
