# .travis.yml
language: node_js

node_js:
  - "node"

install:
  - npm install -g wait-on
  - cd backend
  - npm install
  - cd ../frontend
  - npm install

script:
# Check frontend can be run without error
  - npm run dev & wait-on http://localhost:8080
# Build frontend for production
  - npm run build
  - cd ../backend
# Check backend can be run without error
  - npm start & wait-on http://localhost:3000
