environment:
  npm_version: latest
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm --version
  - cd backend
  - npm install
  - cd ../frontend
  - npm install
  - cd ..

test_script:
  - node --version
  - npm --version
# Check frontend can be run without error
  - cd frontend
  - SET DEBUG=backend:*
  - npm run dev & sleep 10
# Build frontend for production
  - npm run build
  - cd ../backend
# Check backend can be run without error
  - npm start & sleep 5
  - cd ..

build: off
