environment:
  npm_version: latest
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "11"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm --version
  - cd backend
  - npm install
  - cd ../frontend
  - npm install
  - cd ..

test_script:
  - node --version
  - npm --version
# Check frontend can be run without error
  - cd frontend
  - ps: $locfg = Get-Location
  - ps: $jobfg = Start-Job -ArgumentList $locfg -ScriptBlock {Param($x); npm run dev --prefix $x}; sleep 20
  - ps: Receive-Job $jobfg
  - ps: Stop-Job $jobfg
# Build frontend for production
  - npm run build
# Check backend can be run without error
  - cd ../backend
  - ps: $locbg = Get-Location
  - ps: $jobbg = Start-Job -ArgumentList $locbg -ScriptBlock {Param($x); npm start --prefix $x}; sleep 10
  - ps: Receive-Job $jobbg
  - ps: Stop-Job $jobbg
  - cd ..

build: off
