version: '3'

services:
  blocktensor-backend:
    build: ./backend
    container_name: blocktensor-backend
    ports:
      - '3000:3000'
      - '8080:8080'
  blocktensor-frontend:
    build: ./frontend
    container_name: blocktensor-frontend
    depends_on:
      - blocktensor-backend
    network_mode: "service:blocktensor-backend"
