version: '3'

services:
  blocktensor-backend:
    build: ./backend
    container_name: blocktensor-backend
    ports:
      - '3000:3000'
    deploy:
      restart_policy:
        condition: on-failure
  blocktensor-frontend:
    build: ./frontend
    container_name: blocktensor-frontend
    ports:
      - '8080:8080'
    depends_on:
      - blocktensor-backend
    deploy:
      restart_policy:
        condition: on-failure
