version: 2
jobs:
  deploy:
    machine:
      enabled: true
    working_directory: ~/blocktensor
    filters:
      branches:
        only: master
    steps:
      - run:
          name: 'Deploy to Heroku'
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker build --rm=false -t registry.heroku.com/blocktensor/web
            docker push registry.heroku.com/blocktensor/web:latest

workflows:
  version: 2
  workflow:
    jobs:
    - deploy
