version: 2
jobs:
  build:
  deploy:
    machine:
      enabled: true
    filters:
      branches:
        only: master
    steps:
      - run:
        name: 'Deploy to Heroku'
        command: |
          docker login --email=$HEROKU_LOGIN --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
          docker build --rm=false -t registry.heroku.com/blocktensor/web .
          docker push registry.heroku.com/blocktensor/web:latest
