version: 2
jobs:
  build:
    machine:
      enabled: true
    filters:
      branches:
        only: master
    steps:
      - checkout
      - run:
          name: 'Deploy the docker image'
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker build --rm=false -t registry.heroku.com/blocktensor/web .
            docker push registry.heroku.com/blocktensor/web:latest
      - run:
          name: 'Setup Heroku'
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
      - run:
          name: 'Deploy to Heroku'
          command: |
            heroku container:release web --app blocktensor

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
